### PR TITLE
English: add a footnote for clarity

### PR DESCRIPTION
**Pull request by mremy**
Verify, but it looks words are fliped.

### CODE REVIEW

**Comment by mremy** [comment]
I checked again, and I guess I misundertood here. (and PR should be rejected)
Scalar: only one value per XMM register.
Single: stand for single precision (float).

**Comment by mremy** [comment]
I did a "push --force", to squash commits.
I edited too the PR title.
Works as expected :-)

**Comment by DennisYurichev** [comment]
Merci!

**Comment by DennisYurichev** [comment]
https://github.com/DennisYurichev/RE-for-beginners/commit/4b0c17ccc19d26b4872e27880edd24227d3334d9

**Pull request merged**
